//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCSImport
    {
        public int id { get; set; }
        public string LineBlob { get; set; }
        public Nullable<int> DocNumber { get; set; }
        public string Location { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
    public partial class Source
    {
        public int Id { get; set; }

        public string MachineName { get; set; }

        public string Name { get; set; }

        public string IPAddress { get; set; }
    }

    public class sourceDocInfo
    {
        public int DocNumber { get; set; }
        public string LastPath { get; set; }
    }

    public class MCSPage
    {
        public string user { get; set; }
        public string password { get; set; }
        public List<MCSImport> mcsobj { get; set; }
    }
    public class RootObject
    {
        public MCSImport[] mcs { get; set; }
    }
}
